{{- $storage := index .Values "aws-compatible-storage" }}
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: {{ .Values.namespace }}
spec:
  apiServer:
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
    caBundleFileMountPath: ''
    caBundleFileName: ''
    cacheEnabled: false
    pipelineStore: database
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      host: {{ include "agent-mesh.awsCompatibleStorage.fullname" . }}.{{ .Values.namespace }}.svc.cluster.local
      port: {{ include "agent-mesh.awsCompatibleStorage.apiPort" . | quote }}
      scheme: http
      secure: false
      region: {{ $storage.s3.region }}
      bucket: {{ .Values.pipelineStorage.bucket }}
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: {{ include "agent-mesh.awsCompatibleStorage.secretName" . }}
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
