apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: {{ .Values.namespace }}
spec:
  apiServer:
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
    caBundleFileMountPath: ''
    caBundleFileName: ''
    cacheEnabled: false
    pipelineStore: database
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      host: s4.{{ .Values.namespace }}.svc.cluster.local
      port: "7480"
      scheme: http
      secure: false
      region: {{ .Values.s4.s3.region }}
      bucket: {{ .Values.pipelineStorage.bucket }}
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: s4-credentials
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
