name: Nightly - agent-mesh-for-sw-modernization (main)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  test:
    uses: ./.github/workflows/test-agent-mesh-for-sw-modernization.yml
    with:
      branch: main
    secrets: inherit
